--******************************************
-- 09_02_Viewing_Statistics.sql
--******************************************

USE AdventureWorks2014;
GO

-- set the statistics options to on in order to display information
-- related to the query processing.  
-- Uncomment each SET STATISTICS statement below to see what it does.

-- Displays the number of milliseconds required to 
-- parse, compile, and execute each statement.
--SET STATISTICS TIME ON


-- Causes SQL Server to display information regarding the amount 
-- of disk activity generated by Transact-SQL statements.
--SET STATISTICS IO ON


-- Displays the profile information for a statement. 
-- STATISTICS PROFILE works for ad hoc queries, views, and stored procedures.
--SET STATISTICS PROFILE ON


-- Causes Microsoft SQL Server to execute Transact-SQL statements 
-- and generate detailed information about how the statements were 
-- executed in the form of a well-defined XML document
--SET STATISTICS XML ON
GO

-- Smple query to show execution plan for a single SELECT statement
SELECT *
FROM Person.Person;
GO

-- You can also set the STATISTICS to OFF once your query has executed.
--SET STATISTICS TIME OFF
--SET STATISTICS IO OFF
--SET STATISTICS PROFILE OFF
--SET STATISTICS XML OFF

-- Select the product name from the Production.Product table
-- combine that with the comments and product review ID from the ProductReview table
-- using the ProductReviewID to establish the relationship
SELECT p.Name, pr.ProductReviewID, pr.Comments
FROM Production.Product p
INNER JOIN Production.ProductReview pr
ON p.ProductID = pr.ProductID;
GO


